version: '3.8'

services:
  db:
    build: ./initdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  create:
    build: ./create
    ports:
      - "8001:8001"
    depends_on:
      - db

  read:
    build: ./read
    ports:
      - "8002:8002"
    depends_on:
      - db

  update:
    build: ./update
    ports:
      - "8003:8003"
    depends_on:
      - db

  delete:
    build: ./delete
    ports:
      - "8004:8004"
    depends_on:
      - db
   
  nginx:
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - create
      - read
      - update
      - delete

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always


volumes:
  db_data:


