apiVersion: v1
kind: Service
metadata:
  name: devops-python-service
spec:
  selector:
    app: devops-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
  
